name: Documentation
on:
  pull_request:
    paths:
      - '.github/workflows/documentation.yml'
      - 'package.json'
      - 'docs/**'
      - 'lib'
      - 'test'
      - 'website.js'
      - 'CHANGELOG.md'
  push:
    branches:
      - master
    paths:
      - '.github/workflows/documentation.yml'
      - 'package.json'
      - 'docs/**'
      - 'lib'
      - 'test'
      - 'website.js'
      - 'CHANGELOG.md'
permissions:
  contents: read

jobs:
  lint-documentation:
    runs-on: ubuntu-latest
    name: Lint Markdown files
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4

      - name: Setup node
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: 16

      - run: npm install

      - name: Lint MD-Files # run markdownlint
        run: npm run lint-md

      # enable when "eslint-markdown" can be used without errors
      # - name: Lint JS-Files # run eslint to lint the code-blocks themself
      #   run: npm run lint-js

  test-documentation:
    runs-on: ubuntu-20.04
    name: Test Generating Docs
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
      - run: git fetch --depth=1 --tags # download all tags for documentation

      - name: Setup node
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: 16

      - run: npm install
      - name: Setup MongoDB
        run: |
          wget -q https://downloads.mongodb.org/linux/mongodb-linux-x86_64-ubuntu2004-5.0.14.tgz
          tar xf mongodb-linux-x86_64-ubuntu2004-5.0.14.tgz
          mkdir -p ./data/db/27017 ./data/db/27000
          printf "\n--timeout 8000" >> ./test/mocha.opts
          ./mongodb-linux-x86_64-ubuntu2004-5.0.14/bin/mongod --setParameter ttlMonitorSleepSecs=1 --fork --dbpath ./data/db/27017 --syslog --port 27017
          sleep 2
          mongod --version
          echo `pwd`/mongodb-linux-x86_64-ubuntu2004-5.0.14/bin >> $GITHUB_PATH
      - name: Setup config
        run: |
          echo "module.exports = {uri:'mongodb://127.0.0.1:27017/mongoose_test'};" > ./.config.js
      - run: npm run docs:clean
      - run: npm run docs:generate
