name: Typescript Types
on:
  pull_request:
    paths:
      - '.github/workflows/tsd.yml'
      - 'package.json'
      - 'types/**'
      - 'test/types/**'
  push:
    paths:
      - '.github/workflows/tsd.yml'
      - 'package.json'
      - 'types/**'
      - 'test/types/**'
permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint TS-Files
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4

      - name: Setup node
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: 18

      - run: npm install

      - name: Lint TS-Files
        run: npm run lint-ts

  test-ts-types:
    needs:
      - lint
    runs-on: ubuntu-latest
    name: Test Typescript Types
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4

      - name: Setup node
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: 14

      - run: npm install

      - name: Typings
        run: npm run test-tsd
